 
  name: External Workflow 
  on: 
    workflow_dispatch: 
  jobs: 
    external-job: 
      runs-on: ubuntu-latest 
      steps: 
        - name: Run external job 
          run: echo "Выполняется внешний воркфлоу!" 
      