name: Create and Upload Test Artifact to Azure File Share
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a test artifact
      run: |
        mkdir -p artifact
        echo "This is a test artifact" > artifact/test-file.txt

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: test-artifact
        path: artifact/test-file.txt

    #- name: Install Azure CLI
    #  run: |
    #    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Get current date
      if: always()
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Compress report directory
      if: always()
      run: |
        zip -r "playwright-report-test-${{ env.CURRENT_DATE }}.zip" artifact/


    - name: Upload report to Azure File Share
      if: always()
      run: |
        az storage file upload \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --share-name ${{ secrets.AZURE_FILE_SHARE }} \
          --source "playwright-report-test-${{ env.CURRENT_DATE }}.zip" \
          --path "playwright-report-test-${{ env.CURRENT_DATE }}.zip" \
          --sas-token "${{ secrets.AZURE_STORAGE_SAS_TOKEN }}"

      
